---
kind: ConfigMap
apiVersion: v1
metadata:
    name: cm
    namespace: default
data:
    foo: bar
---
kind: ConfigMap
apiVersion: v1
metadata:
    name: special-config
    namespace: default
data:
    specialip: '{{ .Pod.PodIP }}'
    speciallabels: '{{ .Pod.Labels }}'
    specialname: '{{ (.ConfigMap "cm").foo }}'
---
