apiVersion: v1
kind: Pod
metadata:
 name: dapi-test-pod
 labels:
   label1: label1value
   label2: label2value
spec:
 containers:
   - name: test-container
     image: gcr.io/google_containers/busybox
     command: [ "/bin/sh", "-c", "cat /etc/config/*"]
     env:
     - name: LOCAL_IP
       valueFrom:
         configMapKeyRef:
           name: special-config
           key: special.ip
     - name: LOCAL_LABELS
       valueFrom:
         configMapKeyRef:
           name: special-config
           key: special.labels
     - name: LOCAL_NAME
       valueFrom:
         configMapKeyRef:
           name: special-config
           key: special.name
     volumeMounts:
     - name: config-volume
       mountPath: /etc/config
 volumes:
   - name: config-volume
     downwardAPI:
         items:
             - path: "cfg"
               configMapRef: "special-config"
               template: |
                   TEMPLATED FILE...
                   {{ special.labels }}
                   {{ special.name }}
             - path: "labels"
               fieldRef: 
                   fieldPath: "metadata.labels"
 restartPolicy: Never
