apiVersion: v1
kind: Pod
metadata:
 name: dapi-test-pod
 labels:
   label1: label1value
   label2: label2value
spec:
 containers:
   - name: test-container
     image: gcr.io/google_containers/busybox
     command: [ "/bin/sh", "-c", "sleep 3 && echo -- Rendered file -- && cat /etc/config/cfg && echo -- ConfigMap files cat-ed -- && cat /etc/config2/*"]
     env:
     - name: LOCAL_IP
       valueFrom:
         configMapKeyRef:
           name: special-config
           key: specialip
     - name: LOCAL_LABELS
       valueFrom:
         configMapKeyRef:
           name: special-config
           key: speciallabels
     - name: LOCAL_NAME
       valueFrom:
         configMapKeyRef:
           name: special-config
           key: specialname
     volumeMounts:
     - name: config-volume
       mountPath: /etc/config
     - name: config-volume2
       mountPath: /etc/config2
 volumes:
   - name: config-volume
     downwardAPI:
         items:
             - path: "cfg"
               configMapRef: "special-config"
               template: |
                   TEMPLATED FILE...
                   {{ .speciallabels }}
                   {{ .specialname }}
             - path: "labels"
               fieldRef: 
                   fieldPath: "metadata.labels"
   - name: config-volume2
     configMap:
         name: special-config
 restartPolicy: Never
